### PR TITLE
New version

### LINKED ISSUE #221: WS/ASGI “no route found for path”
Hello,

The websocket connection seems to be broken. I keep seeing the error mentioned above.

I notice that `embark/embark/routing.py` mentions being the equivalent of `urls.py` but it is not the same.

`embark/embark/urls.py` shows the inclusion of `embark/reporter/urls.py` which then contains the variable `EMBA_LOG_URL` containing the proper file location. Is this missing from ASGI?

I cannot otherwise seem to find where the file location is being passed to Daphne when executing `run-server.sh`.

Please let me know what you think.

### PR DESCRIPTION
**Pull request by BenediktMKuehne**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---
- fix #221 
- add access permissions for features
- small additions

**What is the current behavior?** (You can also link to an open issue here)
---
-

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---
better

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---
nope

**Other information**:
---

### CODE REVIEW

**Comment by secsonthebeach** [comment]
Hello, thank you for looking into this issue.
I have cloned from here https://github.com/BenediktMKuehne/embark/tree/new-version and reinstalled using this repo.
I am still seeing the same error for both ‘view log’ and on the progress page.

Should I have run this using the Dev or debug flags?

**Comment by BenediktMKuehne** [comment]
🤔 that really is the strangest thing
Could you check if the developer installation is working for you?
`installer.sh -F`

Thanks for testing btw, I appreciate it

**Comment by secsonthebeach** [comment]
The developer install ran successfully. Recall I am setting this up behind firewall.  

Using a dynamic port forward to the host I am working from, I was able to load the HTTP interface in a proxied browser. I observed the same behavior of successful upload and analysis of a small firmware image. I was able to view the raw log file, but did not observe any ‘live stream’ of the progress or log. I did observe the network calls for `ws/progress` and `ws/logs/<file-id>` in the browser tools.

Additionally, I used the `websocat` tool again from the embark host to attempt to hit those same URL paths.

Both the proxied browser and the local tool return ‘500 Internal Sever Error’

The cloned repository path + `logs/daphne.log` shows the same errors as before, “no route found for path” for both ‘/ws/progress’ and ‘/ws/logs’. The trace back looks the same for both paths:

```
 ERROR Exception inside application: No route found for path '/ws/logs/e277aaaa-8a8
f-4a58-b528-3ff6291fbeb1'.
Traceback (most recent call last):
  File "/home/embark/.venv/lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/home/embark/.venv/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/embark/.venv/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/embark/.venv/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/embark/.venv/lib/python3.10/site-packages/channels/middleware.py", line 24, in __cal
l__
    return await self.inner(scope, receive, send)
  File "/home/embark/.venv/lib/python3.10/site-packages/channels/routing.py", line 116, in __call_
_
    raise ValueError("No route found for path %r." % path)
```

**Comment by BenediktMKuehne** [comment]
I'm starting to suspect some dependency issue, there were no changes to the ASGI in the last few months

**Comment by BenediktMKuehne** [comment]
Might be differences between the Daphne versions...will check

**Comment by BenediktMKuehne** [comment]
image

**Comment by secsonthebeach** [comment]
Hello, thank you for working on this.
I’ve pulled your recent changes, but cannot seem to install. I keep getting an error, “Looks like your docker container is outdated - please update your base image”
I removed all images and ran it again, but get the same thing.
I currently have the Emba docker image v1.5.0b, which says is “latest”

**Comment by secsonthebeach** [comment]
I’ve pulled and installed with both of above commits. The install succeeds, but I am unable to navigate to the page getting either 403 or 404 errors.

For both commits, installing with -d displays an error when running the server:
”( 98 ) Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0.:80
No listening sockets available, shutting down
AH00015: Unable to open logs”

I am seeing a similar issue when installing with ‘-F’ and running the debug server. The only thing I can see in the stdout is a reference to a host name on my local domain that I am not familiar with, and telling me that it does not resolve to what I think is the docker network.

**Comment by BenediktMKuehne** [comment]
> I’ve pulled and installed with both of above commits. The install succeeds, but I am unable to navigate to the page getting either 403 or 404 errors.
> 
> For both commits, installing with -d displays an error when running the server: ”( 98 ) Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0.:80 No listening sockets available, shutting down AH00015: Unable to open logs”
> 
> I am seeing a similar issue when installing with ‘-F’ and running the debug server. The only thing I can see in the stdout is a reference to a host name on my local domain that I am not familiar with, and telling me that it does not resolve to what I think is the docker network.

That's the apache still running.
Either remove the apt package: `sudo apt remove apache2 -y` or disable it `sudo systemctl stop apach2`

It's installed for dev but not used at the moment

**Review by m-1-k-3 — APPROVED** [review]
What a beauty :) Good work

**Comment by secsonthebeach** [comment]
This works for me. Thank you!

**Pull request merged**
