### PR TITLE
fix status calc on non phase output

### PR DESCRIPTION
**Pull request by BenediktMKuehne**
Fixe calculation when no phase changes occur

### CODE REVIEW

**Comment by gitsang** [comment]
Closes #196

**Comment by torabi12** [comment]
I think this issue belongs to this section:

image


The progress bar cannot follow the real scan's state.

**Comment by BenediktMKuehne** [comment]
Does the PR fix the issue?
I was only able to test it on a single firmware

**Comment by torabi12** [comment]
I am going to try it, I need some days...

**Comment by torabi12** [comment]
My new test try was hanging at 46% for a day. Some Radare related processes were running and I killed them but they started again and again. So I stopped the test and restarted it with disabled S12, S13, S14, S15 and S16. I hope this outcome will be better.

**Comment by torabi12** [comment]
Sorry, but I got the same with this modified release:

image

If you need some files or info from the system please let me know...

**Comment by BenediktMKuehne** [comment]
Will check this
Do you have a testing firmware for me?

**Comment by torabi12** [comment]
> Will check this Do you have a testing firmware for me?

I sent it to you in email.

**Review by m-1-k-3 — APPROVED** [review]

**Pull request merged**
