### PR TITLE
121 main dashboard empty and bugged

### PR DESCRIPTION
**Pull request by BenediktMKuehne**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---
- fixes main-dash display bug #121
- adds system_bins to main-dash

**What is the current behavior?** (You can also link to an open issue here)
---
#121
& empty row

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---
main dashboard works again

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---
just making sure the migrations run properly (dashboard.result)

### CODE REVIEW

**Comment by torabi12** [comment]
I tested today the dashboard but after the scan it remained empty for me.

**Comment by BenediktMKuehne** [comment]
> I tested today the dashboard but after the scan it remained empty for me.

fresh install and this branch?

**Comment by torabi12** [comment]
> > I tested today the dashboard but after the scan it remained empty for me.
> 
> fresh install and this branch?

I used this command to get it:
`$ git clone https://github.com/BenediktMKuehne/embark.git -b 121-main-dashboard-empty-and-bugged`
on a clean Ubuntu Server 22.04.02

and I used a common D-Link FW.

**Comment by BenediktMKuehne** [comment]
> > > I tested today the dashboard but after the scan it remained empty for me.
> > 
> > 
> > fresh install and this branch?
> 
> I used this command to get it: `$ git clone https://github.com/BenediktMKuehne/embark.git -b 121-main-dashboard-empty-and-bugged` on a clean Ubuntu Server 22.04.02
> 
> and I used a common D-Link FW.

Ok I'll test it again

**Comment by torabi12** [comment]
> > > > I tested today the dashboard but after the scan it remained empty for me.
> > > 
> > > 
> > > fresh install and this branch?
> > 
> > 
> > I used this command to get it: `$ git clone https://github.com/BenediktMKuehne/embark.git -b 121-main-dashboard-empty-and-bugged` on a clean Ubuntu Server 22.04.02
> > and I used a common D-Link FW.
> 
> Ok I'll test it again

I used this binary:
http://files.dlink.com.au/products/DCS-932L/REV_A/Firmware/dcs932l_v1.14.04.bin

I did only one scan, maybe it was an issue on my side, I don't know.

**Comment by BenediktMKuehne** [comment]
image

should work now

**Comment by torabi12** [comment]
> image
> 
> should work now

On my side also works:

kép

**Review by HoxhaEndri — APPROVED** [review]

**Pull request merged**
