### PR TITLE
196 scanning cannot be completed correctly

### PR DESCRIPTION
**Pull request by BenediktMKuehne**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---
work-around for db timeouts

**What is the current behavior?** (You can also link to an open issue here)
---
problems with long scans

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---
fixed?

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---
no

### CODE REVIEW

**Comment by torabi12** [comment]
Something not ok on my side. I downloaded this:

`$ git clone --branch 196-scanning-cannot-be-completed-correctly https://github.com/BenediktMKuehne/embark.git`

Uploaded the iso from the bug:
android-x86_64-9.0-r2.iso

kép

when I hit Analyze I get 500:

kép

**Comment by torabi12** [comment]
Only the android-x86_64-9.0-r2.iso dropped 500, I tried another binary and EMBArk is started the scan:

kép

**Comment by torabi12** [comment]
I started a new test with a binary that was never available under EMBArk.
I hope this will show that the web site can handle long runs.

**Comment by torabi12** [comment]
The scan in EMBArk has been running since 2 and half days and I think it will never finish:

image

I try to execute the same in emba to see the running time.

**Comment by BenediktMKuehne** [comment]
image

image

fixed problems with APK extractor log output

**Review by m-1-k-3 — APPROVED** [review]

**Pull request merged**
